language: android

android:
  components:
    - sys-img-armeabi-v7a-android-21
    - build-tools-21.1.2
    - android-21

script:
  - ./gradlew clean build connectedCheck coveralls

cache:
  directories:
    - $HOME/.m2
